# Generated by Django 5.2.7 on 2026-01-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_user_id_cd4f27_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_notific_a659f1_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_reminder', 'Appointment Reminder'), ('system', 'System')], default='system', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
